# Generated by Django 5.0.6 on 2024-06-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilebanner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webbanner',
            options={},
        ),
    ]
