# Generated by Django 5.0.6 on 2024-06-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_mobilebanner_size_webbanner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/default/product.jpg', null=True, upload_to='uploads/products'),
        ),
    ]
