# Generated by Django 5.0.6 on 2024-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/pic.png', null=True, upload_to='uploads/products'),
        ),
    ]
